# Site settings
title: 3Pats
email: to3pats@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Canadian economics and politics data visualizations by Patrick C. Clarke
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://3pats.ca" # the base hostname & protocol for your site
twitter_username: threepats
github_username:  pcclarke
paginate: 10

# Build settings
markdown: kramdown

# Plugins
gems: ["jekyll-paginate"]